aspire:  
  webdriver:
     scope: restart 
     #thread is the default
   
  console: 
  # turn it to false upon run it on jenkins
    enabled: false 
  
  
  dashboard:
    integration:
     enabled: true
     host: 82.212.71.230
     port: 5070
     path: api
     protocol: http
     logLevel: FULL
     projectId: 531
     summary-report-template: ./Summary_Report_Template.txt
      
  
      
  jbehave:
    meta-data:
    - +production 
    thread: 1
    story-time-out: 3000 
    rerun: 1
    softassert: 
      enabled: true 
    stories:
      defaultloader:
        enabled: true   
        include: 
          #Run one story - stories/02-Profile/TC-001-ExistenceOf(PROFILE).story
          #Run all stories - stories/**/**.story
          #Run all folder stories - stories/01-login/**.story
          #Run some sequance stories - stories/05-Physics Today/TC-01**.story //(TC-01 ,TC-010 ,TC-011,TC-012 -...-TC-019)
         
          - stories/**/**.story
         
          
          
     
          
       
  screenshot:
    enabled: true
    only-on-failure: true
    filesaver:
      enabled: true
      folder-location: ./screenshots/

spring:
  output:
    ansi:
      enabled: always  
logging:
  level: 
    com:
      aspire: DEBUG
  file: application_zurqan.log  


    
server:
  port: 9090







   